trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you need

- script: |
    # Your Python script commands go here
    python -m pip install -r requirements.txt  # Install any required packages
    python your_script.py  # Replace with the actual name of your Python script
  displayName: 'Run Python Script'
